//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ufba.ShHome
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "vShome";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"ShHome";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Ufba";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID ShHomeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ShHomeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID ShHomeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ShHomeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewShHomeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(ShHomeCommandSetId), 0x0001);
	
		// Package identifier
		public const string ShHomePackageId = "77ffa719-c0b9-4ca6-be18-1ca75620562f";
		
		// Editor factory identifier
		public const string ShHomeEditorFactoryId = "0eb83710-3bb5-41eb-94d9-0d57d5ce3ca7";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string ShHomeModelExplorerToolWindowId = "d0ca3013-ad3a-40eb-91f8-98480563e21f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Ufba.ShHome
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string ShHomeCommandSetId = "5d2a4fd0-d1cc-4c48-beb1-1da56aa67269";
	}
}